authentik:
  authentik:
    secret_key: ""
    existingSecret:
      secretName: authentik-credentials
    postgresql:
      password: ""
  postgresql:
    enabled: true
    auth:
      existingSecret: authentik-credentials
      secretKeys:
        adminPasswordKey: AUTHENTIK_POSTGRESQL__PASSWORD
        userPasswordKey: AUTHENTIK_POSTGRESQL__PASSWORD
  redis:
    enabled: true
  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - auth.ruddenchaux.xyz
      tls:
        - secretName: authentik-tls
          hosts:
            - auth.ruddenchaux.xyz
