---
- name: Configure DHCPv6-PD client on WAN interface
  ansible.builtin.include_tasks: dhcpv6-pd.yml

- name: Assign IPv6 addresses from pool to VLAN interfaces
  ansible.builtin.include_tasks: ipv6-addresses.yml

- name: Configure Router Advertisements on VLAN interfaces
  ansible.builtin.include_tasks: router-advertisements.yml

- name: Configure IPv6 firewall rules
  ansible.builtin.include_tasks: firewall.yml
