---
mikrotik_bridge: bridge
mikrotik_trunk_port: ether6

vlans:
  - id: 10
    name: management
    gateway: 10.10.0.1/24
    comment: Management VLAN
  - id: 20
    name: trusted-lan
    gateway: 10.20.0.1/24
    comment: Trusted LAN VLAN
  - id: 30
    name: kubernetes
    gateway: 10.30.0.1/24
    comment: Kubernetes VLAN
