apiVersion: v2
name: monitoring
description: kube-prometheus-stack umbrella chart (Prometheus + Grafana)
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: "81.6.9"
    repository: https://prometheus-community.github.io/helm-charts
