apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-ui-tls
  namespace: kube-system
spec:
  secretName: hubble-ui-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - hubble.ruddenchaux.xyz
