all:
  children:
    vps:
      hosts:
        vps-relay:
          ansible_host: 89.167.62.126
    proxmox:
      hosts:
        pve:
          ansible_host: 10.10.0.2
          ansible_user: root
    mikrotik:
      hosts:
        mikrotik-gw:
          ansible_host: 192.168.88.1
    k8s:
      children:
        k8s_control_plane:
          hosts:
            k8s-ctrl-01:
              ansible_host: 10.30.0.10
        k8s_workers:
          hosts:
            k8s-worker-01:
              ansible_host: 10.30.0.11
            k8s-worker-02:
              ansible_host: 10.30.0.12
            k8s-worker-03:
              ansible_host: 10.30.0.13
