all:
  children:
    proxmox:
      hosts:
        pve:
          ansible_host: 10.10.0.2
          ansible_user: root
    mikrotik:
      hosts:
        mikrotik-gw:
          ansible_host: 192.168.88.1
