proxmox_api_token: ENC[AES256_GCM,data:26Be0XbUBC08PZ8MfFL+Qcl8H+/Hrbc13uiryvHtdbsaqt1/zn/l2VPwRtxxlE+YDrUgK68nT0rNgA==,iv:v6K/TUlorGm/gisUtjDMBwmEO2P+Me3+SasGK2xg9m0=,tag:EMcyfbwj3v8hXVjSpQ+G+g==,type:str]
sops:
    age:
        - recipient: age18nas3jz5knygax063tjeek855fx69jc3ycn9kzn9qxpdnhe3957s8dz9ky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTclBLZzBoNEVGektkOEJm
            RVFqNlNjT3lxMWVETTRqaGs0Znl3UGhyNVM0CkFWQnFmWkVvRGtnd25td2kyREtG
            Vlg3NDJCR3daLzhjVWk5MmlWNkJxZVUKLS0tIHF5ekJwNDQrZjFTRkQxT2ZVSUZs
            N0xkeXRDR2l0OWdDZVp6Y3dGTFFnTUEK7w6rYkk2ct3da+v5zgNwc8KBC1y1PDkW
            V/paK+SV7qnFCi4MwDC5vIxpXhmgx/p9lpLRmUBB50vozIHtXHWORg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T15:41:42Z"
    mac: ENC[AES256_GCM,data:vAEewF9OZN1JEEAV4mV2EdBsLU5HQddkG4ezPMbp1/7bcwlX3P+dHKgsphj3mXaRsqy9wbiq0FU76NesUkux5Gm/4gsuREt5QO1sPiuHUwp3dJROtnnEVxQk2gsk8SfJhV8ymQNyfNhu9iiF8O/MBYekSvPR30QfSzvbdTbkjI0=,iv:6qIHZWD7K18Z3yrMo9hCSmj1Ysu9GXkZbexH2ZK4MMw=,tag:P6QQdD96+9kMorDVPkgLSA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
