---
- name: Prepare all Kubernetes nodes
  hosts: k8s
  roles:
    - k8s-prerequisites

- name: Initialize Kubernetes control plane
  hosts: k8s_control_plane
  roles:
    - k8s-control-plane

- name: Join worker nodes to cluster
  hosts: k8s_workers
  serial: 1
  roles:
    - k8s-workers
