---
- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    update_cache: true
  notify: Reboot if required

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required
  notify: Reboot if required
  changed_when: reboot_required.stat.exists
