apiVersion: v2
name: traefik
description: Traefik ingress controller umbrella chart
version: 0.1.0
dependencies:
  - name: traefik
    version: "34.3.0"
    repository: https://traefik.github.io/charts
