traefik:
  service:
    type: LoadBalancer
  api:
    dashboard: true
  additionalArguments:
    - "--entryPoints.web.http.redirections.entrypoint.to=:443"
    - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
    - "--entryPoints.web.http.redirections.entrypoint.permanent=true"
  ingressRoute:
    dashboard:
      enabled: true
      matchRule: Host(`traefik.ruddenchaux.xyz`)
      entryPoints:
        - websecure
      tls:
        secretName: traefik-dashboard-tls
