---
collections:
  - name: community.routeros
    version: ">=2.0.0"
  - name: ansible.netcommon
    version: ">=5.0.0"
  - name: kubernetes.core
    version: ">=3.0.0"
  - name: community.general
    version: ">=8.0.0"
