cloudflare_api_token: ENC[AES256_GCM,data:a/RaYasxkEKiri5Sjp4n56OkBBo4DfUw5rwqS5nNE1Quws6qz/IYJw==,iv:Tm42u+G/iCQlfp++nMLmndwejJGxe5Y8PCB3JN9gAAA=,tag:E92rTsalr9ElNa38n4JPBQ==,type:str]
cloudflare_zone_id: ENC[AES256_GCM,data:MmTjRPlmO8OAaN+mhi6rQPZcxzEn8rEetYfUnOPVd/4=,iv:nP/GWHkltUzI/TROq2rvNS2JkXwZ4wgp9ivIYn0+qz8=,tag:V3XzyzBW+QEw4WZwTYT7tg==,type:str]
mullvad_wireguard_private_key: ENC[AES256_GCM,data:SExvcfyIbvw1rV3mIYsKVyNKXbnvpjjT7YicaxtyVueKqr7hx/XUHr5p7DY=,iv:KBMhnk/ZEDY2cZILOAHBaIagTyZVP2+UgFeO4ZQCPZA=,tag:jOubBGX8oEze05CRSG4bQA==,type:str]
mullvad_wireguard_address: ENC[AES256_GCM,data:p+0PLhFIUB92sFOyKb4H,iv:2IxW+TbEK3tXMT2ZCBFNRaNb8ceQ1RoXwTX/ZMeAmcs=,tag:WN5aDkciY/bB34yhV3x6ow==,type:str]
proxmox_api_token: ENC[AES256_GCM,data:z/8nwGW1Ijw8uRgBeq2hCOaVBB2W2YcfaOeCph5LONaHD6JIx4N87z2NLCT4CgUsGcpRJM58PJVo+w==,iv:b7xOegsmangEWGoEHHb4g3H3onwe+uLRHWelj7PsLew=,tag:Ha+Dkr7rLe+qMgwBhwsOXA==,type:str]
vps_public_ip: ENC[AES256_GCM,data:8rmRKlXroS2bGVH+MA==,iv:uVmZeXveLWHXIb4xnGPzSur84A/PnTrmA572uG55KrI=,tag:tG8erQW2HZmyfJH4l+SENw==,type:str]
acme_email: ENC[AES256_GCM,data:svVSEJPO2PBA0lMJnT464E1vuuEPzw==,iv:8gmHBRcg3ihNnerJSwKpVaoQQRCA0Cuuee6+2Nt2KE4=,tag:lHTjsdZ26h8Hgd+U9Q7aTw==,type:str]
sops:
    age:
        - recipient: age18nas3jz5knygax063tjeek855fx69jc3ycn9kzn9qxpdnhe3957s8dz9ky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRK0pZR204WnF6a3lNRGpS
            QjUvUjVjam1Kd25xcGRGak10d0dPT1A4ZW5JCnNtSEZiNmtvR1lyMVpFRFdHWVJH
            M1JpQ3RkWFFMMEM2SkFXNmNSQWNvR0kKLS0tIGU0SG9TcXRWTHpoUUp3SjFxa1Z0
            MVd5bWJjb05MRmZKSVVtRTljZlY4VEEK8mK8tHV0fs8KZPhe/SBSwHhfOlYqh82J
            W0qtSm0479U3K5Q+DFHIwCkVexMLiXWJCQ4okoioLy+6tzBg8fJZFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T16:44:33Z"
    mac: ENC[AES256_GCM,data:L8r/jH97zoy2r/FYIfBWjyzcUk1hqJKfVI7FQ2reWjj7oNVzhoQPTPdJuhh7X4az6QoM103nM2xGswLNjfWkhlPoZ2IbDSr8Vi3dDovt0fWxrJh/i1jXUT4Dj+icuvZ6FtDJ7QvXTaXYs/JVsey7/q45CiSmpnQRiJhQ1QHta+8=,iv:+NCrrixX0ThyKMcvtd7w520yRlWJyuWGPRDLgdOqMP8=,tag:Z2wSqBUh24nnlC0YWKB6Mw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
