cloudflare_api_token: ENC[AES256_GCM,data:vTaL1ctemNop7nBzBY66it8WEZIiTMCCm3SYTFh5R7+yjt0JF8CCZA==,iv:bOsIpScGxTQaNHyT3Ht+FlcUtyQA5Z3yh+SEJO+ODTk=,tag:aeIyk8Ymb4JSbvawLQVBlA==,type:str]
cloudflare_zone_id: ENC[AES256_GCM,data:c0EpRFjf8PbdCGndhUrWwLE3X/QXdB66CIOoDlczJbI=,iv:pNzdz2bMQ7hZyVfxsdT63aakrFXNF0NO6wRnDO175xU=,tag:KzmggNrGaVhhoM09o80eWw==,type:str]
nordvpn_wireguard_private_key: ENC[AES256_GCM,data:IrV2QPjeNAeeWH+JVjOpcsW1cBSUPzteiD61Hi4bp7bmWwADb8h6w44Tphw=,iv:L67WJs5K6UFUYoxgarEQqku5mh2tNV1xytmlbLiIoak=,tag:azqwPS3iKNe74qk2rvZBVg==,type:str]
proxmox_api_token: ENC[AES256_GCM,data:0QAMgC0XVByM/Ww9KP1DmEsYITy3rzX2hqO3727XWnwyf1tjXuY+jETGOYrguDHI6u4G1CGiD1i1OQ==,iv:oZFQMdxp0nT5jL0N+eiY97PxQpwA/lHuKsOG/8nH7T8=,tag:jVbXFSaGAiKtlPiyCOuUSg==,type:str]
vps_public_ip: ENC[AES256_GCM,data:K5xHz1q66zZn+kRHWA==,iv:z4xfxj8VhsxMo5Bd47TbyUf0I1efrn/dvh+EIqsvntw=,tag:wmmzxVZZ1Bc63X74ziImrg==,type:str]
acme_email: ENC[AES256_GCM,data:HhPZPhMRqbsH2z7wk5PK+YfHqxdCHg==,iv:ol9iO/OxR1wFWLEopLyy8gANLS3Ka7H2ql93/sokfjc=,tag:8Jg+BU/iFfwso7Pw0IoIEg==,type:str]
sops:
    age:
        - recipient: age18nas3jz5knygax063tjeek855fx69jc3ycn9kzn9qxpdnhe3957s8dz9ky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRXVueWFuN0FaZjFiK29J
            eXRQSjYzdlhGZHpsemNFVHVjekJ3TGYxYmtJCm9HTDFpUWlLT1Q4NkNLd2lFdzBR
            emI5Z3lYd3ROUzFESmZLWm9oWUtVSk0KLS0tIGZjOHozcEtOQVRDS0hWV3o0ZW03
            T3BPNFdBTTc4MFNrd1BlRzJnZnZ5UE0KQerM+L9wVIx1XvLBKm2rwFzy0EEyaYvg
            HCqxRMcIH0UidYhXkmnIRjPsXy64BuR4nddhVkNhuAs3OjrsbysBfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T15:41:10Z"
    mac: ENC[AES256_GCM,data:bI3NBn6otUS1fDX3nvVmui980lAXZUfWAe4rI8Jr/9aMtM5Psu5I2kSgqFM8SfPSAsbPAzS3Ei5ZD2YsTFVAaeRqB8FhVHVzBzOGmqdSB/+dbaaJQT0zsO9g9bvEKxuIGhAd1KJFl281qYvpaGCKm1VIPZPer1NVlT13Ut+VTZA=,iv:SxCo7GZAK5O85ZlqNE2WrZM1hJ5oT/BSjjkeTXoy78A=,tag:IYT/+tbENtQFPA763CmlWQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
