cloudflare_api_token: ENC[AES256_GCM,data:T48XVfHVif/LoIwQ43QzU9PPK6TCyxs1LZlGL3fv4W86uPDngaiylA==,iv:WSyTh7+zDnrEiPm8bkjq7tbs5lU3p18DSHdOtAMs4wg=,tag:/FwBLWhhfbg4KMmNLYAUSg==,type:str]
cloudflare_zone_id: ENC[AES256_GCM,data:pL048d2pHQbUy7KcfcS9ttqxseAzk0rSDT7rkmp9W1o=,iv:BJFeE89q20T6ISS8JwVpwL6uVfVnEC+SRYC6CPUH4Vw=,tag:v9J4G/xkiL+7ZpXWBflEyA==,type:str]
nordvpn_wireguard_private_key: ENC[AES256_GCM,data:mkqBRJGbQgboRfAcVOJ0SPV6ELaIF0yoS5skOR2i0TYkAvlCJ5hKzbRHqck=,iv:Si8ksz6+Y1b4vgkQXk0G+KldkpdqCzKeCiocrQZs3gc=,tag:lunEcIxu9zv9wHBPKXMvxg==,type:str]
proxmox_api_token: ENC[AES256_GCM,data:Hb0yWRbTGWAkwjBB4YMxpOEoNc6qQn9QkkWG9tyeQqWh2xKNKKSP39mcyS1tFVlGNBv9cU9527QWgg==,iv:52I5kgT+GQ0+QCeOg0g43vFuj/mkn/B7jH5f7a3d9UQ=,tag:/9sXosEz3rMmqM4tCb0g1Q==,type:str]
vps_public_ip: ENC[AES256_GCM,data:fT0IU99xLt9VWNzwtA==,iv:2ur6nV1yB6HWpc8nk4o18deMrkmaDHSMkp2VS/20tA4=,tag:tzkYe+o33lpWs6st19go1g==,type:str]
acme_email: ENC[AES256_GCM,data:OQ9V3xjYxQcxjq4uwwHHDUZKQ4x7kQ==,iv:dmZ5QZ4nnY1rYHTyzi9aocyLxzTJO6Mn3ZPfKkyIsm8=,tag:EqY+U0q7X/owx4aRvTGiow==,type:str]
sops:
    age:
        - recipient: age18nas3jz5knygax063tjeek855fx69jc3ycn9kzn9qxpdnhe3957s8dz9ky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaK2lqYytKSFlsWmRnRHpE
            Ym9GT2g0cDA5djZjVFFXYmNwUnpoYlNCQW04CkVOQ1JBdlJ2YXhzT1pudEpwSDQ2
            QnUxNmJGZ2NoVTV0aDNXRjlkMVZXMDgKLS0tIFR0azFOM3IveUtibEtpMU5CV25K
            S2NOcllWVmZGMzBvT3NNV1IzaXRyeGcK8IkJnn0NEmGRzXrHlEnRS2NDHFDQJsGH
            N8IxrEWF1VBTJvREhD7nWXYx9qkPqC4UkbByogM5OFLO3YmvHWgO7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T17:15:54Z"
    mac: ENC[AES256_GCM,data:LXm7Gp1tnPyXr5dJGrzmEH8Y8d+kXQucSY3/X0tfLsrnmCXA9RDTB2v6Lb/rIfJCM0eCRVrNiWL/eCv55CsHof1SJp/k0hNXJm1QCUNErhsUw8oYZujAg0nDlfWHvuL1gytbBWJO/L2AIGokvPVPVt4gMxLRlkZt7vofTMe3uFY=,iv:/jUKH+cBLccCxbDX3IqoYJGK35q4LUeqv7LB+74b67A=,tag:PjFy7phWkO7K/j65+6tXmA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
