argo-cd:
  configs:
    params:
      server.insecure: true
    cm:
      url: https://argocd.ruddenchaux.xyz
      oidc.config: |
        name: Authentik
        issuer: https://auth.ruddenchaux.xyz/application/o/argocd/
        clientID: $oidc.authentik.clientID
        clientSecret: $oidc.authentik.clientSecret
        requestedScopes: ["openid", "profile", "email", "groups"]
    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        g, authentik Admins, role:admin
  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: argocd.ruddenchaux.xyz
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik-auth@kubernetescrd
