apiVersion: v2
name: homepage
description: Homepage app launcher umbrella chart
version: 0.1.0
dependencies:
  - name: homepage
    version: "2.1.0"
    repository: https://jameswynn.github.io/helm-charts
